In [100]:
import re
import os
import time
start = time.time()
dfWarn = pd.DataFrame()
DBName = 'NA'
mypath = r"C:\Users\singhs113\Desktop\crmlogs\logs"
for path, subdirs, files in os.walk(mypath):
    for name in files:
        if re.search(r'dev_.*.log$', name, re.IGNORECASE) is not None:
            print(name)
            if re.search(r'(alert_)(.*?\.)', name, re.IGNORECASE) is not None:
                DBName = re.search(r'(alert_)(.*?\.)', name, re.IGNORECASE).group(2).rstrip('.')
            f = open(os.path.join(path, name),'r')
            data = f.read()
            pattern = "([a-zA-Z]{3} [a-zA-Z]{3} \d{2} \d{2}:\d{2}:\d{2} \d{4})(.*?)(?=[a-zA-Z]{3} [a-zA-Z]{3} \d{2} \d{2}:\d{2}:\d{2} \d{4})"
            mappedFile = re.findall(pattern, data, re.DOTALL)
            
            def getwarnings(x):
                a=[]
                string =  ''.join(x)
                if re.search(r'[a-zA-Z]{3} [a-zA-Z]{3} \d{2} \d{2}:\d{2}:\d{2} \d{4}',string,re.DOTALL):       
                    timestamp=re.search(r'[a-zA-Z]{3} [a-zA-Z]{3} \d{2} \d{2}:\d{2}:\d{2} \d{4}', string,re.DOTALL).group(0)
                    old_date = datetime.strptime(timestamp, "%c")
                    new_date = old_date.strftime("%m/%d/%Y")
                    new_time = old_date.strftime("%X")
                if re.search(r'(WARNING:.*?)(?=ORA-\d+)', string,re.DOTALL) is not None: 
                    a = ["NA","NA","NA","NA","NA"]
                    a[0]=new_date
                    a[1]=new_time 
                    a[2]=DBName
                    a[3]=re.search(r'(WARNING:.*?)(ORA-\d+)', string,re.DOTALL).group(1)
                    a[4]=re.search(r'(WARNING:.*?)(ORA-\d+)', string,re.DOTALL).group(2)
                return a
            
            out = map(getwarnings, mappedFile)
            out = list(filter(None, out))
            f.close()
            warn = pd.DataFrame(out,columns=["DATE","TIME","DBNAME","WARNINGS","ERRORCODE"])
            dfWarn=dfWarn.append(warn,ignore_index=True)                      
#print(len(out[0]))
print("Extraction completed") 
print("--Total Time Taken %s mintues" %((time.time() - start)/60))

alert_AP1.log
5
alert_CP5.log
5
alert_EP1.log
5
alert_FP1.log
5
alert_SP1.log
5
alert_UP2.log
5
alert_VP1.log
5
Extraction completed
--Total Time Taken 2.6200891971588134 mintues

In [101]:
dfWarn

,DATE,TIME,DBNAME,WARNINGS,ERRORCODE
0,10/23/2013,02:04:32,AP1,WARNING: inbound connection timed out (,ORA-3136
1,10/23/2013,02:04:42,AP1,WARNING: inbound connection timed out (,ORA-3136
2,10/23/2013,02:04:52,AP1,WARNING: inbound connection timed out (,ORA-3136
3,10/23/2013,02:05:02,AP1,WARNING: inbound connection timed out (,ORA-3136
4,10/23/2013,02:05:12,AP1,WARNING: inbound connection timed out (,ORA-3136
...,...,...,...,...,...
10718,03/31/2019,09:58:40,VP1,WARNING: inbound connection timed out (,ORA-3136
10719,03/31/2019,10:02:23,VP1,WARNING: inbound connection timed out (,ORA-3136
10720,03/31/2019,21:19:37,VP1,WARNING: inbound connection timed out (,ORA-3136
10721,03/31/2019,21:27:55,VP1,WARNING: inbound connection timed out (,ORA-3136
10722,07/15/2019,06:51:06,VP1,WARNING: inbound connection timed out (,ORA-3136

In [99]:
now=datetime.now().strftime("%d_%m_%Y_%H_%M_%S")
with pd.ExcelWriter("OracleWarnings_"+now+".xlsx") as writer: 
    dfWarn.to_excel(writer, sheet_name='Warnings',engine='xlsxwriter',index=False)